import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const [html, css, script] = await Promise.all([
  readFile("index.html", "utf8"),
  readFile("styles.css", "utf8"),
  readFile("script.js", "utf8"),
]);
const splashEnterCss = css.match(/\.splash-enter\s*\{([^}]*)\}/)?.[1] || "";
const splashTransitionCss = css.match(/\.splash-transition\s*\{([^}]*)\}/)?.[1] || "";
const homeRevealKeyframes = css.match(/@keyframes home-reveal\s*\{([\s\S]*?)\n\}/)?.[1] || "";
const mobileCss = css.match(/@media \(max-width:\s*720px\)\s*\{([\s\S]*?)\n\}\n\n@media \(prefers-reduced-motion/)?.[1] || "";
const desktopDockProfileCss = css.match(/\.dock-profile\s*\{([^}]*)\}/)?.[1] || "";
const desktopDockUnitLogoCss = css.match(/\.dock-unit-logo\s*\{([^}]*)\}/)?.[1] || "";
const desktopFolderCss = css.match(/\.folder-art\s*\{([^}]*)\}/)?.[1] || "";

assert.match(html, /class="splash"/, "first-visit splash should be present");
assert.match(html, /class="splash-content"/, "splash should contain the intro content");
assert.match(html, /ONCHAIN IN MOTION/, "intro should use the selected phrase");
assert.doesNotMatch(html, /ONCHAIN IN MOTION\./, "intro phrase should not include a trailing period");
assert.match(html, /data-pixel-drift/, "intro should include a particle canvas");
assert.match(html, /data-splash-enter/, "intro should include a skip control");
assert.doesNotMatch(html, /class="splash-caption"/, "intro should not show the supporting caption");
assert.match(html, /<button class="splash-enter"[^>]*data-splash-enter>\s*Enter\s*<\/button>/, "intro enter control should only show its label");
assert.doesNotMatch(html, /<button class="splash-enter"[^>]*>[^<]*<span/, "intro enter control should not include a decorative arrow");
assert.match(html, /data-splash-transition/, "intro should include a transition message target");
assert.match(html, /class="dock"/, "social dock should be present");
assert.match(html, /class="dock-profile"/, "dock should include the profile shortcut");
assert.match(html, /class="profile-avatar"[^>]*src="assets\/icons\/favicon\.png"/, "dock profile should use the favicon");
assert.match(html, /class="dock-unit"/, "dock should include the UNIT TX shortcut");
assert.match(html, /href="https:\/\/unittx\.io"/, "UNIT TX shortcut should open the UNIT TX site");
assert.match(html, /class="dock-unit"[^>]*data-tooltip="UNIT TX"/, "UNIT TX shortcut should expose its tooltip label");
assert.match(html, /class="dock-unit"[^>]*title="UNIT TX"/, "UNIT TX shortcut should expose a native hover label");
assert.match(html, /class="dock-unit-logo"[^>]*src="assets\/icons\/unittx-mark\.png"/, "UNIT TX shortcut should use the cleaned transparent mark");
assert.match(html, /class="dock-divider"/, "dock should separate profile and social links");
assert.match(html, /class="about-window"/, "profile shortcut should have an about window");
assert.match(html, /Theo Yang/, "about window should identify Theo Yang");
assert.match(html, /Previously/, "about window should include previous experience");
assert.match(html, /class="desktop"/, "main page should use the desktop project surface");
assert.match(html, /class="desktop-item(?:\s|\")/, "main page should contain desktop project folders");
assert.equal((html.match(/class="desktop-item(?:\s|\")/g) || []).length, 8, "main page should contain eight project folders");
assert.equal((html.match(/class="desktop-label"/g) || []).length, 8, "each desktop folder should show a name label");
assert.equal((html.match(/class="desktop-label-text"/g) || []).length, 8, "each folder name should have a centered text wrapper");
assert.equal((html.match(/class="folder-art /g) || []).length, 8, "each project should use a supplied folder image");
assert.doesNotMatch(html, /class="folder-tab"/, "folder tabs should come from the supplied images");
assert.doesNotMatch(html, /class="folder-body"/, "folder bodies should come from the supplied images");
assert.match(html, /folder-art-yellow/, "ZKPs should use a distinct supplied folder color");
assert.match(html, /folder-art-pink/, "Pixymon should use a distinct supplied folder color");
assert.match(html, /folder-art-green/, "Nansen should use a distinct supplied folder color");
assert.match(html, /folder-art-purple/, "Kalshi should use a distinct supplied folder color");
assert.match(html, /folder-art-blue/, "GitHub Candles should use a distinct supplied folder color");
assert.match(html, /folder-art-tan/, "Tip on Arc should use a distinct supplied folder color");
assert.match(html, /folder-art-navy/, "PIXY Terminal should use a distinct supplied folder color");
assert.match(html, /folder-art-magenta/, "Narkina5 should use a distinct supplied folder color");
assert.match(html, /desktop-status-blue/, "ZKPs should use a blue status dot");
assert.match(html, /desktop-status-kalshi/, "Kalshi should use its brand-colored status dot");
assert.match(html, /desktop-status-navy/, "Tip on Arc should use a dark navy status dot");
assert.equal((html.match(/class="desktop-status /g) || []).length, 8, "each project folder should have a status dot");
assert.doesNotMatch(html, /class="folder-preview"/, "desktop folders should not show project screenshots");
assert.doesNotMatch(html, /class="project-map"/, "main page should not render the card grid");
assert.match(html, /data-project="tip-on-arc"/, "Tip on Arc should have an active project card");
assert.match(html, /data-project="pixy-terminal"/, "PIXY Terminal should have an active project card");
assert.match(html, /data-project="narkina5"/, "Narkina5 should have an active project card");
assert.match(script, /image: "assets\/projects\/zkps\.png"/, "ZKPs detail should use its supplied image");
assert.match(script, /image: "assets\/projects\/pixymon-fit\.png"/, "Pixymon detail should use its fitted image");
assert.match(script, /image: "assets\/projects\/github-candles\.png"/, "GitHub Candles detail should use its supplied image");
assert.match(script, /image: "assets\/projects\/kalshi\.png"/, "Kalshi detail should use its supplied image");
assert.match(script, /image: "assets\/projects\/pixy-terminal\.png"/, "PIXY Terminal detail should use its supplied image");
assert.match(script, /image: "assets\/projects\/nansen\.png"/, "Nansen detail should use its supplied image");
assert.match(script, /image: "assets\/projects\/narkina5\.png"/, "Narkina5 detail should use its supplied image");
assert.match(script, /"tip-on-arc"/, "Tip on Arc should be included in project data");
assert.match(script, /"pixy-terminal"/, "PIXY Terminal should be included in project data");
assert.match(script, /narkina5/, "Narkina5 should be included in project data");
assert.match(css, /\.desktop[\s\S]*position:\s*relative/, "project surface should behave like a desktop");
assert.match(css, /\.desktop-item[\s\S]*position:\s*absolute/, "desktop folders should have freeform positions");
assert.match(desktopFolderCss, /width:\s*80px;[\s\S]*height:\s*66px;/, "desktop folders should use a smaller portrait ratio");
assert.match(css, /\.desktop-item-zkps[\s\S]*--desktop-tilt:\s*0deg/, "folders should sit upright");
assert.match(css, /\.site-header[\s\S]*justify-content:\s*flex-start/, "Theo Yang should sit at the left edge of the page");
assert.match(css, /\.brand[\s\S]*color:\s*#fff/, "Theo Yang should use white text");
assert.match(css, /\.folder-art img[\s\S]*object-fit:\s*fill/, "supplied folder images should fill the stable icon frame");
assert.match(css, /\.desktop-label\s*\{[\s\S]*justify-content:\s*center/, "folder labels should center beneath their folders");
assert.match(css, /\.desktop-item-kalshi[\s\S]*white-space:\s*nowrap/, "Kalshi title should stay on one clean line");
assert.match(css, /\.desktop-item-zkps[\s\S]*--desktop-left:\s*6%[\s\S]*--desktop-top:\s*30%/, "ZKPs should sit at position 1");
assert.match(css, /\.desktop-item-pixymon[\s\S]*--desktop-left:\s*21%[\s\S]*--desktop-top:\s*10%/, "Pixymon should sit at position 2");
assert.match(css, /\.desktop-item-nansen[\s\S]*--desktop-left:\s*40%[\s\S]*--desktop-top:\s*15%/, "Nansen should sit at position 3");
assert.match(css, /\.desktop-item-kalshi[\s\S]*--desktop-left:\s*78%[\s\S]*--desktop-top:\s*10%/, "Kalshi should sit at position 4");
assert.match(css, /\.desktop-item-github[\s\S]*--desktop-left:\s*90%[\s\S]*--desktop-top:\s*30%/, "GitHub Candles should sit at position 5");
assert.match(css, /@media \(min-width:\s*721px\) and \(max-width:\s*900px\)[\s\S]*\.desktop-item-github[\s\S]*--desktop-left:\s*88%/, "GitHub Candles should fit inside tablet content width");
assert.match(css, /\.desktop-item-tip[\s\S]*--desktop-left:\s*78%[\s\S]*--desktop-top:\s*84%/, "Tip on Arc should sit at position 6");
assert.match(css, /\.desktop-item-terminal[\s\S]*--desktop-left:\s*42%[\s\S]*--desktop-top:\s*62%/, "PIXY Terminal should sit at position 7");
assert.match(css, /\.desktop-item-narkina[\s\S]*--desktop-left:\s*61%[\s\S]*--desktop-top:\s*48%/, "Narkina5 should sit at position 8");
assert.match(css, /\.desktop-status[\s\S]*border-radius:\s*50%/, "status dots should be round");
assert.match(css, /\.project-dialog-art[\s\S]*object-fit:\s*contain/, "project details should preserve the full supplied image");
assert.doesNotMatch(html, /class="list-section"/, "main page should not render the old writing list");
assert.doesNotMatch(html, /class="entry"/, "main page should not render text entries");
assert.doesNotMatch(html, /class="window-controls"/, "about window should not use macOS traffic lights");
assert.doesNotMatch(html, /class="codex-window-label"/, "about window should not show a Codex label");
assert.doesNotMatch(html, /About Theo Yang/, "about window should not repeat the About Theo Yang phrase");
assert.match(html, /<script defer src="script\.js"><\/script>/, "interaction script should be loaded");
assert.match(html, /href="https:\/\/github\.com\/starlash7"/, "dock should link to GitHub");
assert.match(html, /href="https:\/\/medium\.com\/@pixy7"/, "dock should link to Medium");
assert.match(css, /\.dock-item:hover/, "dock hover state should be styled");
assert.match(css, /\.dock\s*\{[\s\S]*bottom:\s*54px/, "dock should sit above the bottom edge");
assert.match(css, /\.dock-unit\s*\{/, "UNIT TX shortcut should share the dock treatment");
assert.match(css, /\.dock-unit\s*\{[\s\S]*padding:\s*5px/, "UNIT TX logo should use a comparable visual scale");
assert.match(css, /\.dock-unit\s*\{[\s\S]*overflow:\s*visible/, "UNIT TX tooltip should not be clipped by its button");
assert.match(css, /\.dock-unit-logo[\s\S]*object-fit:\s*contain/, "UNIT TX logo should fit inside its dock button");
assert.match(desktopDockProfileCss, /border:\s*0/, "desktop profile shortcut should not show an outer border");
assert.match(desktopDockUnitLogoCss, /width:\s*75%[\s\S]*height:\s*75%/, "desktop UNIT TX logo should be visually larger");
assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.dock-profile\s*\{[\s\S]*border:\s*0/, "mobile profile shortcut should not show an outer border");
assert.match(mobileCss, /\.desktop-item\s*\{[^}]*width:\s*56px/, "mobile folder buttons should use the compact size");
assert.match(mobileCss, /\.folder-art\s*\{[^}]*width:\s*56px;[^}]*height:\s*46px/, "mobile folders should use the compact size");
assert.match(mobileCss, /\.desktop-label\s*\{[^}]*width:\s*56px;[^}]*max-width:\s*56px/, "mobile labels should align with the compact folders");
assert.match(mobileCss, /\.desktop\s*\{[\s\S]*height:\s*calc\(100svh - 18px\)/, "mobile project surface should fit the viewport height");
assert.match(mobileCss, /\.desktop-item-pixymon[\s\S]*left:\s*calc\(100% - 56px\)/, "mobile right folders should sit against the content edge");
assert.match(mobileCss, /\.desktop-item-github[\s\S]*left:\s*0/, "mobile left folders should sit against the content edge");
assert.match(mobileCss, /\.desktop-item-tip[\s\S]*top:\s*clamp\(/, "mobile bottom folders should stay above the dock across viewport heights");
assert.match(css, /@media \(max-width:\s*720px\)[\s\S]*\.dock-unit-logo\s*\{[\s\S]*width:\s*75%/, "mobile UNIT TX logo should match the social icon scale");
assert.doesNotMatch(css, /width:\s*135%/, "UNIT TX logo should not overflow its mobile button");
assert.match(css, /prefers-reduced-motion/, "reduced-motion behavior should be styled");
assert.match(css, /font-family:[\s\S]*Inter/, "site should use the new sans-serif type stack");
assert.match(css, /url\("assets\/background\.png"\)/, "site should use the supplied background image");
assert.match(css, /url\("assets\/background-mobile\.png"\)/, "mobile should use the supplied portrait background image");
assert.match(mobileCss, /body\s*\{[\s\S]*padding-bottom:\s*0/, "mobile should not reserve an extra page-height below the content");
assert.match(mobileCss, /\.page-shell\s*\{[^}]*padding:\s*18px 0 0;/, "mobile page shell should end at the viewport content");
assert.match(css, /\.splash[\s\S]*background:\s*#050505/, "intro should use a black background");
assert.match(css, /\.pixel-drift-canvas[\s\S]*cursor:\s*crosshair/, "intro canvas should support pointer interaction");
assert.match(css, /background-size:\s*cover/, "supplied background should cover the viewport");
assert.doesNotMatch(homeRevealKeyframes, /transform:/, "home reveal should not move fixed background layers");
assert.doesNotMatch(css, /background: #e3d7c7/, "main profile should not use a beige background");
assert.doesNotMatch(css, /background: #e9e2d8/, "dock profile should not use a beige background");
assert.doesNotMatch(script, /localStorage/, "intro visibility should not depend on local storage");
assert.doesNotMatch(script, /theo-yang-intro-v2-seen/, "intro should not be hidden after the first visit");
assert.doesNotMatch(script, /splashWasSeen/, "intro should not track a previous visit");
assert.match(script, /if \(reducedMotion\) \{[\s\S]*hideSplash\(\);/, "only reduced-motion users should skip the intro");
assert.match(script, /prefers-reduced-motion/, "splash should respect reduced motion");
assert.match(script, /getContext\("2d"\)/, "intro should render particles on canvas");
assert.match(script, /cancelAnimationFrame/, "intro particles should stop their animation loop");
assert.match(script, /particleAnimationFrame/, "intro should track one particle animation frame");
assert.match(script, /sampleStep = canvasWidth < 600 \? 4 : 5/, "mobile intro should use a lighter particle sample");
assert.match(script, /const initialParticleSpread = 10/, "intro particles should start close to their text targets");
assert.match(script, /const hideSplash = \(\) => splash\.classList\.add\("is-hidden"\)/, "remembered intro should be able to hide itself");
assert.match(script, /pixelDriftText = "ONCHAIN IN MOTION"/, "intro particle text should be configurable");
assert.doesNotMatch(script, /pixelDriftText = "ONCHAIN IN MOTION\."/, "intro particle text should not include a trailing period");
assert.match(script, /transitionText = "entering the world\."/, "intro should type the entry transition message with a period");
assert.doesNotMatch(script, /transitionText = "entering the world"[^.]/, "intro transition message should include the trailing period");
assert.match(script, /pixelDriftCanvas\.addEventListener\("pointermove"/, "intro particles should respond to the pointer");
assert.match(script, /splashEnter\?\.addEventListener\("click", enterSplash\)/, "intro should enter through the button");
assert.match(script, /setTimeout\(typeNext/, "intro transition should type one character at a time");
assert.doesNotMatch(script, /setTimeout\(hideSplash, 2600\)/, "intro should not auto-enter before the button is pressed");
assert.doesNotMatch(script, /splash\.addEventListener\("click", hideSplash\)/, "intro background should not act as the enter control");
assert.match(css, /\.splash\.is-transitioning/, "intro should style its transition state");
assert.match(script, /\["#c6e9ff", "#ffffff", "#ffd8b8"\]/, "intro should use sky, cloud, and pale-orange particle colors");
assert.match(splashTransitionCss, /color:\s*#fff/, "entry transition text should be white");
assert.match(splashTransitionCss, /font-size:\s*clamp\(0\.78rem/, "entry transition text should be compact");
assert.match(splashTransitionCss, /font-weight:\s*400/, "entry transition text should use a lighter weight");
assert.doesNotMatch(splashEnterCss, /border-bottom:/, "intro enter control should not have an underline");
assert.doesNotMatch(script, /dock\.addEventListener\("pointermove"/, "dock should not magnify on pointer movement");
assert.match(script, /aboutWindow/, "profile window behavior should be wired");
assert.match(script, /projectWindow/, "project detail behavior should be wired");

console.log("Static site structure checks passed.");
